const mongoose=require("mongoose");
const admitStudentSchema=mongoose.Schema({
    name:{
        type:String,
        required:true
      },
      fathername:{
          type:String,
          required:true
      },
      mothername:{
          type:String,
        required:true
      },
      email:{
          type:String,
          required:true,
          unique:true
      },
      dob:{
          type:Date,
        required:true
      },
      bloodgp:{
          type:String,
        required:true
      },
      mobileno:{
          type:Number,
        required:true,
        unique:true
      },
      nationality:{
          type:String,
        required:true
      },
      religion:{
          type:String,
          required:true
      },
      address:{
          type:String,
        required:true
      },
      state:{
          type:String,
        required:true
      },
      pincode:{
          type:Number,
        required:true
      },
      corresaddress:{
          type:String,
        required:true
      },
      corresstate:{
          type:String,
        required:true
      },
      correspincode:{
          type:Number,
        required:true
      },
      exam:{
          type:String,
        required:true
      },
      selectionexamrollno:{
        type:Number
      },
      year:{
          type:Number,
        required:true
      },
      
      rank:{
          type:Number,
        required:true
      },
      score:{
          type:Number,
        required:true
      },
      degree:{
          type:String,
        required:true
      },
      branchname:{
          type:String,
        required:true
      },
      coursename:{
          type:String,
        required:true
      },
      session:{
          type:String,
        required:true
      },
      admissiondate:{
          type:Date,
        required:true
      },
      eno:{
        type:Number
    },
    rollno:{
        type:Number
    },
      admissionno:{
          type:Number,
        required:true
      },
      coursesession:{
        type:String
      },
      currentsemester:{
        type:Number
      },
      paymentmode:{
          type:String,
        required:true
      },
      amount:{
          type:Number,
        required:true
      },
      paymentdate:{
          type:Date,
        required:true
      },
      bankname:{
          type:String,
        required:true
      },
      yearofpayment:{
          type:Number,
        required:true
      },
      password:{
          type:String,
      }
});
module.exports=mongoose.model("AdmitStudent",admitStudentSchema);